import { StyleSheet } from "react-native";
import { YoColors } from "../themes/YoColors";

export const uploadStyles = StyleSheet.create({
  fileUploadCard: {
    height: 109,
    width: "100%",
    borderRadius: 6,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: YoColors.primary,
    borderWidth: 1,
    borderStyle: "dashed",
    flexDirection: "column",
  },
  fileCard: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: YoColors.primary,
    backgroundColor: "#fff",
    borderWidth: 0.7,
    padding: 5,
    minHeight: 50,
    borderRadius: 6,
    marginTop: 10,
  },
  fileCardNoBorder: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 2,
    marginTop: 5,
  },
  fileIcons: {
    height: 30,
    width: 30,
    borderRadius: 4,
    borderColor: "#CACCCD",
    borderWidth: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 2,
  },
  browseWrapper: {
    backgroundColor: "white",
    width: "100%",
    height: 100,
    position: "absolute",
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 10,
  },
  browseIcon: {
    width: 50,
    height: 50,
    backgroundColor: "#e8eaeb",
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
  },
  browseText: {
    fontSize: 12,
    color: YoColors.primary,
    marginTop: 6,
  },
  headTitle: {
    fontSize: 14,
    color: YoColors.primary,
    fontWeight: "500",
    marginTop: 5,
  },
  subTitle: {
    fontSize: 12,
    lineHeight: 14,
    color: "#797979",
    marginTop: 5,
  },
  btnStyle: {
    minWidth: 160,
    height: 45,
    borderWidth: 1,
    borderRadius: 6,
  },
});
