export default {
  logo: require('../img/YoMentorLogo.png'),
  icon: require('../img/YoMentorAppIcon.png'),
  DefaultUser: require('../img/DefaultUser.png'),
  DefaultBook: require('../img/BookPlaceholder.png'),
  academic: require('../img/academic.png'),
  knowledge: require('../img/knowledge.png'),
  competition: require('../img/competition.png'),
  question: require('../img/question.png'),
  complexity: require('../img/complexity.png'),
  language: require('../img/language.png'),
  subject: require('../img/subject.png'),
  skillsTest: require('../img/skills-test.png'),
  DeleteIcon: require('../img/DeleteIcon.png'),
  confirm: require('../img/confirm.png'),
};
